# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'RENTAM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RENTAM
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'GoogleSignIn'
pod 'GoogleSignInSwiftSupport'


  target 'RENTAMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RENTAMUITests' do
    # Pods for testing
  end

end
